# Generated by Django 4.1.7 on 2023-06-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_zip_upload_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End of trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start of trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='do not use'),
        ),
    ]
