/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    readonly continent: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    readonly country: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    readonly state: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    readonly city: string | null;
}

/**
 * Check if a given object implements the Location interface.
 */
export function instanceOfLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "continent" in value;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "city" in value;

    return isInstance;
}

export function LocationFromJSON(json: any): Location {
    return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'continent': json['continent'],
        'country': json['country'],
        'state': json['state'],
        'city': json['city'],
    };
}

export function LocationToJSON(value?: Location | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

