/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedLocation
 */
export interface PatchedLocation {
    /**
     * 
     * @type {number}
     * @memberof PatchedLocation
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedLocation
     */
    readonly continent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLocation
     */
    readonly country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLocation
     */
    readonly state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedLocation
     */
    readonly city?: string | null;
}

/**
 * Check if a given object implements the PatchedLocation interface.
 */
export function instanceOfPatchedLocation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedLocationFromJSON(json: any): PatchedLocation {
    return PatchedLocationFromJSONTyped(json, false);
}

export function PatchedLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'continent': !exists(json, 'continent') ? undefined : json['continent'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'city': !exists(json, 'city') ? undefined : json['city'],
    };
}

export function PatchedLocationToJSON(value?: PatchedLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

