/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedActivity
 */
export interface PatchedActivity {
    /**
     * 
     * @type {number}
     * @memberof PatchedActivity
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedActivity
     */
    readonly name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedActivity
     */
    readonly activityDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedActivity
     */
    readonly location?: number;
}

/**
 * Check if a given object implements the PatchedActivity interface.
 */
export function instanceOfPatchedActivity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedActivityFromJSON(json: any): PatchedActivity {
    return PatchedActivityFromJSONTyped(json, false);
}

export function PatchedActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedActivity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'activityDate': !exists(json, 'activity_date') ? undefined : (json['activity_date'] === null ? null : new Date(json['activity_date'])),
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function PatchedActivityToJSON(value?: PatchedActivity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

