/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Trip
 */
export interface Trip {
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Trip
     */
    readonly name: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Trip
     */
    readonly tripDate: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Trip
     */
    readonly location: number;
}

/**
 * Check if a given object implements the Trip interface.
 */
export function instanceOfTrip(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "tripDate" in value;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function TripFromJSON(json: any): Trip {
    return TripFromJSONTyped(json, false);
}

export function TripFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trip {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'tripDate': (json['trip_date'] === null ? null : new Date(json['trip_date'])),
        'location': json['location'],
    };
}

export function TripToJSON(value?: Trip | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

